- client/src/pages/Repository/components/DetailsView/index.tsx
-Relocated the logic responsible for updating detail tab data outside of the useEffect block
-Now, the update logic occurs whenever something changes about the system object (e.g. name, subtitle, retired) AND whenever a system object is updated
> address ticket 648

- client/src/pages/Repository/components/DetailsView/DetailsTab/AssetGrid.tsx
- client/src/pages/Repository/components/DetailsView/DetailsTab/ObjectVersionTable.tsx
-address header Notes alignment in versions table
-fix sorting bug in asset grid to handle link types
> UI Asset Grid And Versions Table

- client/src/graphql/index.ts
Client:
* Attempted tweak of network error handling for better detection of and response to telework timeouts
> Telework client tweaks

- client/src/graphql/index.ts
Client:
* Detect and "handle" login redirection sent from F5 telework implementation
> Telework Timeout Debugging, Continued

- client/src/graphql/index.ts
Client:
* Another attempt to execute SAML authentication request, this time by explicitly extracting SAMLRequest and RelayState input vars
> Telework Timeout Debugging, Continued II

- client/package.json
Client:
* Add axios to client build
> Telework Timeout Debugging, Continued III

- client/src/graphql/index.ts
Client:
* Format SAMLAuth Request post body in form likely expected by server, and in a manner that helps to avoid CORS preflight checks
> Telework Timeout Debugging, Continued IV

- server/navigation/impl/NavigationSolr/IndexSolr.ts
It looks to me like this is working properly.  Perhaps an issue here is that the client may be caching Navigation graphql queries and so not getting fresh results when newly ingested content is indexed.
To add another layer of insurance here, this PR implements a full reindex every 30 minutes.
Solr:
* Add full reindex job, scheduled to run every 30 minutes (for now)
> Fix for 655:  reindex Solr content offline

- client/package.json
- client/src/graphql/index.ts
Client:
* Try again to handle F5 telework authentication via redirect in main window
* Remove axios from client
> Telework Timeout Debugging, Continued V

- server/utils/migration/MigrationData.ts
* Next set of scene migration targets
> Scene Migration II

- client/src/pages/Ingestion/components/Uploads/index.tsx
- client/src/store/metadata/index.ts
- client/src/store/vocabulary.ts
- server/graphql/schema/ingestion/resolvers/mutations/ingestData.ts
Scene/Model Updates
-Prevent name and subtitle from being replaced when ingesting a new version
CD Updates
-Correctly route the CD metadata step to CD updates (was formerly routed to Other metadata)
-Added functionality for updating the CD, CD Photo, and CD Files
> Ticket 665 664

- server/utils/migration/SceneMigration.ts
Migration:
* Set license and publication status after ingestion, to ensure that our system object version has been created
> Scene Migration WIP

- server/graphql/schema/asset/resolvers/mutations/uploadAsset.ts
- server/utils/migration/SceneMigration.ts
- server/workflow/impl/Packrat/WorkflowUtil.ts
Workflow:
* Make explicit wait times for upload workflow and model metric extraction workflows
* Increase wait time for model metrics extraction to 10 hours
Migration:
* During migration, do not await model metric calculations on downloads, as this may take a long time for large models
> Migration Scene WIP III

- server/job/impl/Cook/JobCook.ts
- server/utils/helpers.ts
Job:
* Allow 10 simultaneous WebDAV transfers to Cook
* Increase max webdav body length to 100GB
* Update webdav logging to aid with greps
* Added test logic to log stream data writes > 2GB in size
> Scene Migration WIP IV

- server/http/index.ts
- server/http/routes/heartbeat.ts
- server/http/routes/logtest.ts
Added a server route, /heartbeat, which can be used my monitoring to perform server health checks.
HTTP:
* Implemented /heartbeat route and health check testing
> Server /heartbeat route and health check

- server/job/impl/Cook/JobCook.ts
- server/utils/helpers.ts
Migration:
* Stream copy tweaks aimed at getting large WebDAV transfers to work
> Scene Migration WIP V

- server/utils/migration/SceneMigration.ts
Migration:
* Added logging to try to spot why migration stops running
> Scene Migration WIP VII

- server/job/impl/Cook/JobCook.ts
- server/utils/sceneHelpers.ts
Jobs:
* Count 400 errors in addition to connection failures; use either to exit polling loop
System:
* Update SceneHelpers.handleComplexIngestionScene to gather model metrics asynchronously
> Scene Migration WIP VIII

- server/http/routes/migrate.ts
- server/utils/logger.ts
System:
* Increase log file size to 100MB before rolling
Migration:
* Limit migrations to a maximum of 10 at a time
> Scene Migration WIP IX

- server/job/impl/Cook/JobCook.ts
- server/job/impl/NS/JobPackrat.ts
Migration:
* Limit Cook to 25 simultaneous jobs
Job:
* Attempt to enable retry of jobs across Cook server rollover
> Cook Job Limits; Cook Job restart on rollover

- conf/docker/docker-compose.deploy.yml
- conf/docker/server-inspect.Dockerfile
- conf/scripts/deploy.sh
- server/job/impl/Cook/JobCook.ts
Job:
* Only send notification for each failing Cook server once
Build:
* Added inspect taget for deploy.sh script
* Added packrat-client-spect, packrat-server-inspect, and packrat-solr-inspect docker build targets
* Added server-inspect.Dockerfile script for creating the server inspect container, which exposes port 9229 for node debugging, adds additional debugging tools to build image, and starts node in debugging mode via NODE_OPTIONS environment variable
> Scene Migration WIP X

- conf/docker/server-inspect.Dockerfile
- conf/scripts/packs.sh
- package.json
- server/package.json
Try again to get node debugging working via--inspect flag:
Build:
* readd start:server:inspect and start:inspect to package.jsons
* Use start:server:inspect for the inspect-flavored builds
> Scene Migration WIP XI

- conf/docker/server-inspect.Dockerfile
- server/graphql/schema/asset/resolvers/mutations/rollbackAssetVersion.ts
- server/job/impl/Cook/JobCook.ts
- server/storage/impl/LocalStorage/OCFLObject.ts
- server/storage/interface/AssetStorageAdapter.ts
- server/tests/collections/EdanCollection.test.ts
- server/tests/storage/interface/AssetStorageAdapter.test.ts
- server/tests/utils/helpers.test.ts
- server/tests/utils/parser/bulkIngestReader.test.ts
- server/tests/utils/zipStream.test.ts
- server/utils/helpers.ts
We were not calling WriteableStream.end() in a number of critical places; this PR addresses this.
Build:
* Fix typo in server inspect Dockerfile
GraphQL:
Storage:
Test:
* Make sure to close write streams when complete with them
> Address accumulation of open file handles

- conf/docker/docker-compose.deploy.yml
- server/package.json
Build:
* Update inspect to listen on port 9230, and to map host port 9229 to container port 9230
> Inspect Flavor OPS tweaks to enable remote debugging

- server/storage/interface/AssetStorageAdapter.ts
- server/utils/helpers.ts
Storage:
* Attempt to force cleanup of stream used to extract metadata
> Attempt to cleanup open file handles

- client/src/pages/Ingestion/components/Uploads/FileListItem.tsx
- client/src/pages/Ingestion/components/Uploads/SpecialUploadList.tsx
- client/src/pages/Repository/components/DetailsView/index.tsx
- client/src/store/upload.ts
DetailsView/index.tsx
-implement scrolling to special uploader upon rendering
FileListItem.tsx
-address compilation warning for logic handling
-added comment for differentiating between the different FileListItem cases
store/upload.ts
-address folder upload case for in special uploader
> Post-Feedback Fixes

- client/src/pages/Admin/components/Subject/SubjectView.tsx
- client/src/pages/Admin/store/adminSubject.tsx
- client/src/pages/Workflow/components/WorkflowView/WorkflowFilter.tsx
Workflow
Address workflow search not resetting page number to 0
Admin Subjects
Address buggy admin subjects search behavior not respecting asynchronous state changes
Built a new state store AdminSubjects to handle the component
> ticket 692

- server/utils/migration/ModelDataExtraction.ts
* Handle case when OBJs have multiple MTL files
* Add logic for parsing MTL files to identify texture maps
* Avoid using Cook for OBJs (as we're extracting maps ourselves) and PLYs (as our master models have no textures in this format)
* Ingest MTL files so that we can then read their contents to determine referenced texture maps
> Migration: Avoid using Cook for OBJs and PLYs during "migration extraction"

- server/http/routes/migrate.ts
- server/utils/migration/ModelDataExtraction.ts
Migration:
* Wire item to model when migrating models in "extract" mode
* Update model migration extraction script generation
> Migration: model extraction updates

- conf/docker/docker-compose.deploy.yml
- conf/docker/docker-compose.dev.yml
- conf/docker/docker-compose.prod.yml
- conf/scripts/packs.sh
- server/config/solr/etc/default/solr.in.sh
- server/http/routes/migrate.ts
- server/utils/migration/ModelDataExtraction.ts
Build:
* Load solr.in.sh into solr image to increase solrs Java memory limits
* Modify packs.sh helper script to specify root user when connecting to docker containers
Migration:
* Attempt to ingest materials referenced in MTL files
> Really increase RAM available to solr's Java; attempt to ingest materials referenced in OBJs' MTL's

- conf/docker/docker-compose.deploy.yml
- conf/docker/docker-compose.dev.yml
- conf/docker/docker-compose.prod.yml
- conf/docker/solr.Dockerfile
- server/http/routes/migrate.ts
- server/tests/db/composite/Model.setup.ts
- server/utils/migration/ModelDataExtraction.ts
- server/utils/migration/ModelMigration.ts
Build:
* Set execute bit on solr.in.sh, needed to set java memory limits
Migration:
* Prepare to handle full migration set
* Improved detection of texture directives in MTL files
* Ingest explicit support files
> Try again to increase Solr Java memory limits; prep for full model migration list

- server/utils/migration/ModelDataExtraction.ts
* Ensure that we process MTL files just once
* Always skip duplicate support files
* Improve logging
> Migration: process MTL files just once

- .gitattributes
- server/collections/impl/PublishScene.ts
Build:
* Specify EOL of LF for mock data
Collections:
* Note details about scene publishing confirmed by Andrew
> Specify EOL of LF for mock data

- server/utils/migration/ModelMigration.ts
- server/utils/migration/SceneMigration.ts
Migration:
* Rationalize logging
* Don't complain about Scene Name/Title mismatches if the difference is only due to capitalization
> Migration:  logging tweaks

- server/graphql/schema/systemobject/resolvers/queries/getVoyagerParams.ts
Look for preferred asset, and use that to supply Voyager's path and document
> Fix regression in getVoyagerParams 

- conf/nginx/nginx-dev.conf
- conf/nginx/nginx-prod.conf
- server/db/api/WorkflowReport.ts
- server/db/prisma/schema.prisma
- server/db/sql/scripts/Packrat.SCHEMA.sql
- server/graphql/schema/asset/resolvers/mutations/uploadAsset.ts
- server/report/interface/ReportFactory.ts
- server/tests/db/dbcreation.test.ts
- server/utils/zipFile.ts
- server/workflow/impl/Packrat/WorkflowUpload.ts
* switched to streaming approach for file uploads
* removed body size check for Nginx to remove filesize cap when uploading
* added 'Name' to WorkflowReport to assist with identification and file generation
> [DPO3DPKRT-746] fix/large file upload failure (#543)

- conf/nginx/nginx-dev.conf
Fixes [DPO3DPKRT-764](https://jira.si.edu/browse/DPO3DPKRT-764) allowing for easier running of Proxy mode locally through an Nginx change.
> DPO3DPKRT-764/fix local proxy cors conflicts

- server/auth/impl/LDAPAuth.ts
Updating configurations to LDAPS endpoints. 
**Note**: environment variables need to point to ldaps://ldaps.si.edu:636
> DPO3DPKRT-770/Update to LDAPS.

- .gitignore
- server/collections/impl/PublishScene.ts
- server/db/api/ModelSceneXref.ts
- server/db/api/Scene.ts
- server/job/impl/Cook/JobCook.ts
- server/job/impl/Cook/JobCookSIGenerateDownloads.ts
- server/job/impl/Cook/JobCookSIPackratInspect.ts
- server/storage/interface/AssetStorageAdapter.ts
- server/tsconfig.json
- server/utils/logger.ts
- server/utils/migration/SceneMigration.ts
- server/workflow/impl/Packrat/WorkflowEngine.ts
Added support for returned Voyager scene files and additional Draco compressed and USDZ models from the 'si-generate-downloads' recipe.
> DPO3DPKRT-701/generate downloads support for scenes

- server/types/voyager/DocumentValidator.ts
- server/types/voyager/common.ts
- server/types/voyager/document.ts
- server/types/voyager/json/model.schema.json
- server/types/voyager/meta.ts
- server/types/voyager/model.ts
- server/types/voyager/setup.ts
Updated Voyager parsing and validation to support modern features and properties.
> DPO3DPKRT-778/updating Voyager support for modern features

- server/storage/interface/AssetStorageAdapter.ts
- server/utils/nameHelpers.ts
Titles pulled from EDAN resulting in svx filenames with periods caused issues with the storage system.
> (fix) svx failed to ingest with periods in EDAN title

- server/workflow/impl/Packrat/WorkflowUpload.ts
switched to using storage interface for finding staging paths vs. the config.
> [DPO3DPKRT-752] decouple explicit storage path in workflow

- server/types/voyager/document.ts
- server/types/voyager/json/document.schema.json
- server/types/voyager/json/meta.schema.json
- server/types/voyager/meta.ts
(new) support for splash screens and auto near/far plane calculations
> [DPO3DPKRT-800] Update to Voyager Schema for v0.39.0

- client/src/pages/Ingestion/components/Metadata/Control/SceneGenerateWorkflowControl.tsx
- client/src/pages/Ingestion/components/Metadata/Model/index.tsx
- client/src/pages/Ingestion/hooks/useIngest.ts
Updated the UX for a more intuitive experience when ingesting.
- switched to dropdown and label changed to 'Generate Voyager Scene'
- tooltip for detailing the criteria of the dropdown
- fixed bug where scenes always generated independent of setting (defaulted to yes)
> [DPO3DPKRT-793] Voyager scene auto-generation checkbox confusing

- client/src/pages/Ingestion/components/Metadata/Control/SubtitleControl.tsx
- client/src/pages/Ingestion/components/Metadata/Model/ObjectMeshTable.tsx
- client/src/pages/Ingestion/components/Metadata/Model/index.tsx
Organized details returned from model inspection into a collapsible section while improving some layout/styling for ingestion.
> DPO3DPKRT-808/cleaner model details during ingest

- client/src/pages/Ingestion/components/SubjectItem/SubjectListItem.tsx
- client/src/pages/Ingestion/components/SubjectItem/index.tsx
- client/src/pages/Ingestion/components/Uploads/index.tsx
applying changes after rebase re-syncing with master after botched merge.
> Fix: merging after rebase

- .eslintignore
- client/src/config/index.ts
- client/src/pages/Repository/components/DetailsView/DetailsTab/VoyagerExplorer.tsx
- client/src/pages/Repository/components/DetailsView/DetailsTab/VoyagerStory.tsx
- client/src/pages/Repository/components/DetailsView/DetailsThumbnail.tsx
- client/src/pages/Repository/components/DetailsView/VoyagerStoryView.tsx
- Added support for editing Voyager scenes using the entire browser window. 
- Pressing the 'Exit' button in VoyagerStory now closes the editor and returns to the Scene Details page
> DPO3DPKRT-811/Fullscreen Editing of Voyager Scenes

- .github/workflows/ci.yml
- .gitignore
- client/src/pages/Ingestion/components/Metadata/Photogrammetry/AssetContents.tsx
- common/constants.ts
- docs/content/user/vocabulary/_index.md
- package.json
- server/cache/VocabularyCache.ts
- server/db/sql/scripts/Packrat.ALTER.sql
- server/db/sql/scripts/Packrat.DATA.sql
- server/tests/cache/VocabularyCache.test.ts
(new) added 'Masks' to available options for CaptureData variants & updated UX
(new) added tooltip to Variant header with descriptions for each
**Note: DB Update**
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (8, 4, 'Masks');
> DPO3DPKRT-822/Masks variant for CaptureData set

- client/src/pages/Repository/components/DetailsView/DetailsThumbnail.tsx
(fix) Voyager Story popups losing focus preventing user input
(fix) Voyager Story delete article popup showing behind the main UI
> DPO3DPKRT-826/Voyager Story popups preventing user input

- client/src/store/metadata/metadata.defaults.ts
- fixed issue where field validation fails when selecting all 3 Dataset Use properties
> DPO3DPKRT-830/Validating CaptureData use default fails

- server/job/impl/Cook/CookResource.ts
Querying for available Cook resources will now retry 3 times for failed connections due to timeout or DNS issues.
> DPO3DPKRT-832/retrying cook resource connections

- client/src/pages/Admin/components/AdminToolsView.tsx
- Added button to refresh scenes listed for batch downloads
- Added tooltips to configuration and filtering options
> DPO3DPKRT-834/ux manual refresh batch downloads

- server/db/api/WorkflowSet.ts
- server/http/routes/api/generateDownloads.ts
- server/http/routes/api/project.ts
- DPO3DPKRT-841/Server not deploying. Incorrect reference of COMMON (#615)
> (0.9.21f1) Hot Fix: Server not deploying due to COMMON reference

- client/src/pages/Admin/components/AdminToolsView.tsx
- more robust name filtering accounting for special characters and whitespace
- better client side logging around getting project scenes
> DPO3DPKRT-845/Batch Generation not filtering on full name

- client/src/pages/Admin/components/AdminToolsView.tsx
- Cleanup of table cells with tooltips for long text
- Descriptive text to section describing limits
- Table header tooltips
> DPO3DPKRT-840/UX Improvements to Batch Generation

- client/src/api/index.ts
- client/src/pages/Admin/components/AdminToolsView.tsx
- server/http/routes/api/generateDownloads.ts
- server/workflow/impl/Packrat/WorkflowEngine.ts
If a scene was invalid or not eligible for download generation it would throw an exception.
> DPO3DPKRT-843/invalid Scenes Crash Batch Download

- client/src/api/index.ts
- client/src/pages/Admin/components/AdminToolsView.tsx
- server/http/routes/api/generateDownloads.ts
- server/http/routes/api/project.ts
- server/workflow/impl/Packrat/WorkflowEngine.ts
- Production now building correctly after changes to COMMON
- Scenes with errors no longer crashing the batch process + better error handling/messaging
- Cleaner display of a project's scenes + addition of Media Groups to help identify 'presentation' models
- Scene name filtering is now more robust
> (0.9.21f2) Hot Fix: Invalid scenes failing and UX improvements

- server/http/routes/api/project.ts
- (fix) incorrect date and status for downloads. now using latest asset version.
> DPO3DPKRT-847/Incorrect Error State and Download Dates

- server/http/routes/api/project.ts
- Fix generated downloads status and creation date in SceneSummary
> (0.9.21f3) HotFix: Incorrect Downloads Status and Dates

- server/db/api/WorkflowReport.ts
- (fix) incorrect reference to workflow report table when fetching by JobRun
> DPO3DPKRT-849/Prisma cannot find table in Workflow Report

- client/src/pages/Admin/components/AdminToolsView.tsx
- server/http/routes/api/project.ts
- Fix handling of Scene Summary data in the batch admin tool
- Support for exporting table to CSV
> (0.9.22f1) HotFix: Invalid Handling of Scene Summary Data

- client/src/graphql/index.ts
- client/src/store/upload.ts
- client/src/utils/events.ts
- conf/docker/docker-compose.dev.yml
- conf/docker/docker-compose.prod.yml
- conf/nginx/conf.d/common-locations-dev
- conf/nginx/conf.d/common-locations-prod
- conf/nginx/nginx-dev.conf
- conf/nginx/nginx-prod.conf
- server/graphql/api/index.ts
- server/graphql/schema/asset/resolvers/mutations/uploadAsset.ts
- server/http/index.ts
- server/http/routes/errorhandler.ts
- server/job/impl/Cook/JobCook.ts
- server/job/impl/Cook/JobCookSIPackratInspect.ts
- server/storage/impl/LocalStorage/LocalStorage.ts
- server/utils/helpers.ts
Resolving handling of individual and concurrent large file (10GB+) uploads.
- Updated configuration for Docker, GraphQL, ExpressJS to support large files
- Stream handling improved, removing unnecessary 'buffering'
- Logging throughout the upload process (client/server) for transparency
- Upload events carry error messages
> DPO3DPKRT-879/Large File Upload Connection Drop

- client/src/pages/Admin/components/AdminToolsView.tsx
Improved name handling for exporting scene details to CSV
- Sanitize strings prior to CSV export
> DPO3DPKRT-884/Robust Name Handling for Scene Reports

- client/src/pages/Admin/components/AdminToolsView.tsx
- server/http/routes/api/project.ts
Direct control over project selection and reduced server load
- 'All Projects' option when selection projects for Batch Scene Processing
- Batch processing of requests to lessen server load
> DPO3DPKRT-885/Batch Scene Details Support for All Projects

- client/src/pages/Ingestion/components/Metadata/Control/SubtitleControl.tsx
- client/src/pages/Ingestion/components/Metadata/Model/index.tsx
Auto select subtitle option when valid one provided
- Auto selects 'subtitle' field if one is present
- fix Model ingest page initializing Select components to null
> DPO3DPKRT-880/UX Auto-select Ingest Subtitle

- client/src/pages/Ingestion/components/Metadata/Control/SubtitleControl.tsx
- client/src/pages/Ingestion/components/Metadata/Model/index.tsx
- client/src/pages/Ingestion/components/Metadata/Photogrammetry/index.tsx
- client/src/store/metadata/metadata.defaults.ts
Visually mark required fields on ingestion pages + validation fixes
- marked required fields with an astrix
- removed debug items from SubtitleControl
- CaptureData dataset use not triggering validation
> DPO3DPKRT-859/UX Ingestion Mark Required Fields

- client/src/components/shared/AssetIdentifiers.tsx
- client/src/pages/Ingestion/components/Metadata/Control/SubtitleControl.tsx
- client/src/pages/Ingestion/components/Metadata/Model/index.tsx
- client/src/pages/Ingestion/components/Metadata/Photogrammetry/index.tsx
- client/src/pages/Ingestion/components/Metadata/Scene/SceneDataForm.tsx
- client/src/pages/Ingestion/components/Metadata/Scene/index.tsx
- client/src/pages/Ingestion/components/Metadata/index.tsx
- client/src/store/detailTab.tsx
- server/job/impl/Cook/JobCook.ts
Improved Cook response handling for scene/download generation
- Catch unsupported response states
- Better control of workflow timing to ensure consistent outcomes
- Blocking input during ingestion with user notice/guidance
- Date validation preventing same day settings
> (0.9.24b) Hotfix: Cook response handling and Ingestion UX

- client/src/pages/Ingestion/components/Metadata/Photogrammetry/index.tsx
- Remove/Hide unused 'Field ID' option on CaptureData ingestion
> DPO3DPKRT-891/Hide Unused Field IDS

- client/src/pages/Admin/components/AdminToolsView.tsx
- server/auth/AuthRouter.ts
- server/http/routes/api/project.ts
Improved scene reports and identifying ownership
- 'Creator' column and supporting data attached to assets
- Cleanup log statements for scene reports
> DPO3DPKRT-886/Export User ID for Model

- server/cache/VocabularyCache.ts
- server/db/api/CaptureData.ts
- server/db/api/Model.ts
- server/graphql/api/index.ts
- server/http/routes/api/project.ts
CaptureData Support in Reports and Cleanup
- new CaptureData.fetchFromModel() for getting all CaptureData attached to model
- Support for CaptureData status and asset listing in reports
- AR status now correct
- Core derivatives status now accurately reflects Voyager requirements
> DPO3DPKRT-892/CaptureData Support in Reports and Cleanup

- client/src/pages/Ingestion/components/Metadata/Model/index.tsx
- client/src/pages/Ingestion/components/Metadata/Photogrammetry/index.tsx
- client/src/pages/Repository/components/DetailsView/DetailsTab/CaptureDataDetails.tsx
Cleanup ingestion fields and tooltips
- Tooltip for Voyager Scene generation not blocking dropdown
- CaptureData field ID's hidden in details
- Consistent naming for capture data parents/children
> DPO3DPKRT-894/UX Ingest Tooltips and Fixes

- client/src/pages/Admin/components/AdminToolsView.tsx
- client/src/pages/Ingestion/components/Metadata/Model/index.tsx
- client/src/pages/Ingestion/components/Metadata/Photogrammetry/index.tsx
- client/src/pages/Repository/components/DetailsView/DetailsTab/CaptureDataDetails.tsx
- server/auth/AuthRouter.ts
- server/cache/VocabularyCache.ts
- server/db/api/CaptureData.ts
- server/db/api/Model.ts
- server/graphql/api/index.ts
- server/http/routes/api/project.ts
- CaptureData presence included in reports
- AR status for reports more robust
- User creator added to reports
- Ingest UX cleanup (tooltips, data fields, parent/child naming)
> (0.9.25) CaptureData Reporting and Ingest UX Fixes

- client/src/api/index.ts
- client/src/pages/Admin/components/AdminToolsView.tsx
- client/src/pages/Admin/components/Tools/ToolsAssetValidation.tsx
- client/src/pages/Admin/components/Tools/ToolsBatchGeneration.tsx
- client/src/pages/Admin/components/shared/DataTableSelect.tsx
- client/src/pages/Admin/components/shared/DataTypesStyles.tsx
- server/http/index.ts
- server/http/routes/WebDAVServer.ts
- server/http/routes/api/generateDownloads.ts
- server/http/routes/api/report.ts
- server/job/impl/Cook/JobCookSIPackratInspect.ts
- server/storage/impl/LocalStorage/LocalStorage.ts
- server/storage/interface/IStorage.ts
- server/utils/helpers.ts
- Initial implementation of asset validation
- Store results as CSV on the server in Staging/tmp
- Legacy support for Cook ingestion reports and material checks
> (0.9.26) Asset Validation and Legacy Report Handling

- client/src/api/index.ts
- client/src/pages/Admin/components/AdminToolsView.tsx
- client/src/pages/Admin/components/Tools/ToolsAssetValidation.tsx
- server/db/api/CaptureData.ts
- server/db/api/Item.ts
- server/db/api/Project.ts
- server/db/index.ts
- server/http/index.ts
- server/http/routes/api/project.ts
- server/http/routes/api/report.ts
- Listing context (Units, Subjects, etc.) for asset validation
- New utility routines for DB access to Projects, Items, and SystemObjects
- Report storage and UX for downloading reports
> DPO3DPKRT-901/Asset Validator Context and Reports

- client/src/pages/Admin/components/Tools/ToolsBatchGeneration.tsx
- client/src/pages/Admin/components/shared/DataTableSelect.tsx
- client/src/pages/Admin/components/shared/DataTypesStyles.tsx
- client/src/pages/Ingestion/components/Metadata/index.tsx
- server/http/index.ts
- server/http/routes/api/project.ts
- Support for Date Modified on all assets and elements
- Date Created updated to represent capture/create dates
- CSV output updated to take first/last dates for created and modified columns
- CSV CaptureData now displays number of capture datasets present
- Loading indicator when fetching project scenes
> DPO3DPKRT-900/Scene Report Outputs and UX Updates

- client/src/pages/Admin/components/AdminToolsView.tsx
- server/http/routes/api/report.ts
- Refactored asset validation reports to use disk caches
- Sequentially processes each asset leading to less DB or disk thrashing
- Added users to Admin Tools group
> DPO3DPKRT-903/Asset Validation Disk Caching

- client/src/pages/Admin/components/Tools/ToolsBatchGeneration.tsx
- client/src/pages/Admin/components/shared/DataTypesStyles.tsx
- server/http/routes/api/project.ts
- server/http/routes/api/report.ts
- server/storage/impl/LocalStorage/OCFLObject.ts
- Leveraging streams and disk caching for asset validation
- Sequential processing of assets validation
- OCFL validation and hash comparisons
- Improved logging for reports
- Version now represents current asset version vs. total versions
- Capturing 'expected' number of sources for a given MediaGroup
> DPO3DPKRT-902/Asset Validation and Scene Report Fixes

- client/src/pages/Admin/components/Tools/ToolsBatchGeneration.tsx
- client/src/pages/Admin/components/shared/DataTypesStyles.tsx
- server/http/routes/api/project.ts
- AR and CaptureData added to batch download table
- CaptureData status update to include common workflows
- Updated AssetList type to include 'expected' count for determining error state
> DPO3DPKRT-838/Batch Download Column Updates

- declarations.d.ts
- server/db/api/JobRun.ts
- server/db/api/User.ts
- server/db/api/WorkflowStep.ts
- server/db/sql/scripts/Packrat.DATA.sql
- server/http/index.ts
- server/job/impl/Cook/JobCook.ts
- server/job/impl/Cook/JobCookSIGenerateDownloads.ts
- server/job/impl/Cook/JobCookSIVoyagerScene.ts
- server/job/impl/NS/JobPackrat.ts
- server/records/logger/log.ts
- server/records/recordKeeper.ts
- server/types/voyager/common.ts
- server/types/voyager/document.ts
- server/types/voyager/json/document.schema.json
- server/types/voyager/json/setup.schema.json
- server/types/voyager/meta.ts
- server/types/voyager/model.ts
- server/types/voyager/setup.ts
- server/workflow/impl/Packrat/WorkflowIngestion.ts
- server/workflow/impl/Packrat/WorkflowJob.ts
- server/workflow/impl/Packrat/WorkflowUpload.ts
- server/workflow/impl/Packrat/WorkflowUtil.ts
- Email notifications for Upload, Ingest, and Scene/Download Generation
- RecordKeeper pulling user accounts, email preferences, and addresses from DB
- Update Voyager schema to support latest features (e.g. Navigation Modes)
> DPO3DPKRT-865/Introduce Email Notifications

- client/src/pages/Admin/components/AdminToolsView.tsx
- client/src/pages/Admin/components/Tools/ToolsBatchGeneration.tsx
- client/src/pages/Admin/components/shared/DataTypesStyles.tsx
- client/src/store/metadata/metadata.defaults.ts
- declarations.d.ts
- server/db/api/JobRun.ts
- server/db/api/User.ts
- server/db/api/WorkflowStep.ts
- server/http/index.ts
- server/http/routes/api/project.ts
- server/http/routes/api/report.ts
- server/job/impl/Cook/JobCook.ts
- server/job/impl/Cook/JobCookSIGenerateDownloads.ts
- server/job/impl/Cook/JobCookSIVoyagerScene.ts
- server/job/impl/NS/JobPackrat.ts
- server/records/logger/log.ts
- server/records/recordKeeper.ts
- server/storage/impl/LocalStorage/OCFLObject.ts
- server/types/voyager/common.ts
- server/types/voyager/document.ts
- server/types/voyager/json/document.schema.json
- server/types/voyager/json/setup.schema.json
- server/types/voyager/meta.ts
- server/types/voyager/model.ts
- server/types/voyager/setup.ts
- server/workflow/impl/Packrat/WorkflowIngestion.ts
- server/workflow/impl/Packrat/WorkflowJob.ts
- server/workflow/impl/Packrat/WorkflowUpload.ts
- server/workflow/impl/Packrat/WorkflowUtil.ts
- Email notifications for Upload, Ingest, and Scene/Download Generation
- Update Voyager schema to support latest features (e.g. Navigation Modes)
- Refactored asset validation reports to use streams and disk caching
- Improved logging for reports and field representation
- CaptureData status update to include common workflows
- Updated AssetList type to include 'expected' count for determining error state
- RecordKeeper pulling user accounts, email preferences, and addresses from DB
> (0.9.28) Email Notifications & Asset Validation Reports

- conf/scripts/server_ops/backup_data.sh
- conf/scripts/server_ops/backup_db.sh
- conf/scripts/server_ops/backup_logs.sh
- conf/scripts/server_ops/ops_container.sh
- conf/scripts/server_ops/ops_data.sh
- conf/scripts/server_ops/ops_database.sh
- conf/scripts/server_ops/ops_deployment.sh
- conf/scripts/server_ops/ops_diskCleanup.sh
- conf/scripts/server_ops/ops_logLess.sh
- conf/scripts/server_ops/ops_logTail.sh
- conf/scripts/server_ops/ops_menu.sh
- conf/scripts/server_ops/ops_migration.sh
- conf/scripts/server_ops/ops_monitor.sh
- conf/scripts/server_ops/ops_monitorDisk.sh
- conf/scripts/server_ops/ops_monitorFiles.sh
- conf/scripts/server_ops/ops_solr.sh
- conf/scripts/server_ops/ops_system.sh
- Monitor real-time disk usage and performance
- Monitor real-time network usage
- Monitor real-time system resources (cpu, memory, etc.)
- Disk and container cleanup 
- Log utilities equivalent to LESS and TAIL
- Menu for running many common commands
> DPO3DPKRT-915/System Scripts for Server Operations

- server/job/impl/Cook/JobCook.ts
- On success, Cook job is deleted freeing up resources
- Explicit log hooks for future metrics
> DPO3DPKRT-762/Cook Job Cleanup

- server/http/routes/api/project.ts
- Scene reports displaying malformed error for WebAR
> DPO3DPKRT-918/Fix malformed WebAR Report Results

- client/src/pages/Ingestion/components/Metadata/Model/index.tsx
- server/job/impl/Cook/JobCook.ts
- server/utils/helpers.ts
- Cook jobs no longer cleanup prematurely
- Model ingestion metadata has tooltips
- GraphQL log output was not consistent or helpful
> DPO3DPKRT-923/Fix Cook Job Cleanup & Model Tooltips

- client/src/components/controls/ReadOnlyRow.tsx
- client/src/pages/Ingestion/components/Metadata/Scene/index.tsx
- client/src/pages/Repository/components/DetailsView/DetailsTab/SceneDetails.tsx
- client/src/pages/Repository/components/DetailsView/DetailsTab/index.tsx
- client/src/pages/Repository/components/DetailsView/index.tsx
- client/src/store/detailTab.tsx
- client/src/store/metadata/metadata.defaults.ts
- client/src/store/metadata/metadata.types.ts
- server/graphql/schema/systemobject/resolvers/queries/getDetailsTabDataForObject.ts
- server/utils/helpers.ts
- Display 'published url' in Details tab for Scenes
- Passing 'published state' down to all detail pages
> DPO3DPKRT-921/Published Scene Links

- server/collections/impl/EdanCollection.ts
- server/db/api/composite/ObjectGraph.ts
- server/db/api/composite/ObjectGraphDatabase.ts
- server/workflow/impl/Packrat/WorkflowJob.ts
- server/workflow/impl/Packrat/WorkflowUpload.ts
- adjusted log output for ObjectGraph and Workflows
> DPO3DPKRT-927/Log Excessive ObjectGraph  Output

- client/src/api/index.ts
- client/src/pages/Repository/components/DetailsView/ObjectDetails.tsx
- client/src/pages/Repository/components/DetailsView/index.tsx
- server/http/index.ts
- server/http/routes/api/generateVoyagerScene.ts
- server/job/impl/Cook/JobCookSIVoyagerScene.ts
- Update delivered package from client for Scene Generation
> DPO3DPKRT-934/Hotfix For Scene Generation Package

- server/http/routes/api/object.ts
- server/types/voyager/common.ts
- server/types/voyager/document.ts
- server/types/voyager/json/document.schema.json
- server/types/voyager/json/meta.schema.json
- server/types/voyager/json/setup.schema.json
- server/types/voyager/meta.ts
- server/types/voyager/setup.ts
- Scene Status Table now works for all users
- Adjusted authorization requirements for contacts and units as well
> DPO3DPKRT-937/Hotfix: Scene Status Table Fails

- server/http/routes/api/object.ts
- server/types/voyager/common.ts
- server/types/voyager/document.ts
- server/types/voyager/json/document.schema.json
- server/types/voyager/json/meta.schema.json
- server/types/voyager/json/setup.schema.json
- server/types/voyager/meta.ts
- server/types/voyager/setup.ts
* Adjust Auth Requirements for Status Table, Units, and Contacts
* Voyager Schema Update to Latest
> (0.9.32) Hotfix: Scene Status Table Fails and Voyager Update
