Smithsonian/dpo-packrat

server/graphql/schema/ingestion/resolvers/mutations/ingestData.ts

-Only enforce parent model validation for scene ingestion if not updating (i.e. when scene doesn't have idAsset)

ticket 653

---

server/job/impl/Cook/JobCookSIPackratInspect.ts

Cook:
* Updated si-packrat-inspect's test for unzipping to load stream results for the given asset version(s), instead of using the model's name passed in -- the latter may be the name of the uncompressed model file inside a zip

Fix for 659's si-packrat-inspect failures

---

client/src/graphql/index.ts

Client:
* Restore original behavior upon telework SAML reauth responses -- redirect our app back to the login screen.  We need more support here from OCIO to determine and address the underlying issue.

Telework Timeout Debugging, Continued VI

---

client/src/pages/Repository/components/RepositoryTreeView/index.tsx
client/src/store/repository.ts
client/src/utils/repository.tsx
server/utils/parser/bulkIngestReader.ts

Also included a fix for 660.
Client:
* Always reload repository rows when expanding an item.  This allows us to refresh the tree as content is ingested
* Modified Repo Tree's onNodeToggle to determine if a node is being expanded, and if so, delete the children of the specified node from the repository store
* Compute a hierarchy string for tree items recursively, building a hierarchy string of idSystemObject IDs and storing these as part of the tree item's node ID
* Maintain a tree node expandedCount in the repository store; update this via setExpandedCount, which returns whether a node was expanded or collapsed
* Implemented repository store's deleteChildren(), called when expanding a node, to remove that node's information from the tree before we re-query to get that node's children …

Fix for 655 and 656: always reload children of repository item during expansion; Fix for 660

---

client/src/components/controls/CheckboxField.tsx
client/src/pages/Ingestion/components/Uploads/UploadCompleteList.tsx
client/src/pages/Repository/components/DetailsView/DetailsTab/SceneDetails.tsx
client/src/store/metadata/metadata.defaults.ts

671 - Model Ingestion Disallow Future Date
Added additional validation for model ingestion and adding a new version
672 - Env Banner Blocks Uploaded List
Added additional margin to the bottom of the list
673 - Hoverover Tooltip for Posed and QC'd Control 
Added an explicit help icon instead for the tooltip instead of using the checkbox
Removed tooltip feature for <CheckboxField /> as it's no longer needed

Bugfix/671 - 673

---

client/src/pages/Repository/components/DetailsView/ObjectDetails.tsx
client/src/pages/Repository/components/RepositoryTreeView/TreeLabel.tsx
client/src/utils/repository.tsx
server/workflow/impl/Packrat/WorkflowUpload.ts

657 & 658
-During file validating process of uploading asset, return an error if an empty zip is detected
677
-Add hoverover for each repository tree row that indicates the object type
-Modified some of the tree row icon initials
Other
-Revised hoverover behavior of scene publish API buttons in scene details to be consistent with other hoverovers (i.e. no need to click)

address 657, 658, 677

---

server/db/api/composite/SubjectUnitIdentifier.ts
server/tests/db/composite/SubjectUnitIdentifier.test.ts

Test:
* Address regression failures caused by database ID updates.  A better fix is to load these IDs from the database, but I'm taking a shortcut to save time.

Address regression failures

---

server/cache/SystemObjectCache.ts

Doing so results in us eventually exceeding the JS 2^24 entry limit for Maps ... most likely due to auditing attempting to get system objects for all sorts of DB inserts & modifications.

Cache: Avoid adding non-system objects to SystemObjectCache's objectIDToSystemMap

---

server/tests/utils/helpers.test.ts
server/utils/helpers.ts

* Require json-bigint-patch in helpers.ts, so that regression tests pick it up, too.
* Update helpers.test.ts to reflect new serialization of bigints (not as strings)

Regression Failure Fix

---

server/db/prisma/schema.prisma

Build:
* Re-add prisma 'interactiveTransctions' feature to prisma schema, despite an apparently incorrect warning that this statement is deprecated

Build fix for updated prisma version

---

server/utils/migration/ModelDataExtraction.ts

* Await ingestion of explicit support files, to avoid migrating them mulltiple times if they are referenced implicitly, as well

Migration: Await ingestion of explicit support files

---

server/package.json
server/storage/impl/LocalStorage/OCFLObject.ts
server/utils/helpers.ts
server/utils/logger.ts
yarn.lock

System:
* Added winston-daily-rotate-file
* Use winston-daily-rotate-file to rotate logs every day
* Allow Helpers.moveFile to fail without logging an error
* Use Helpers.moveFile without logging an error when the OCFLObject has not yet tried to move a file

Daily log rotation; mark OCFLObject move operations that fail as an error when appropriate

---

server/package.json
server/tests/teardown.ts
server/utils/logger.ts
yarn.lock

Build:
* Roll back to Prisma v4.8.1 to avoid leading handle at test exit
Test:
* Disconnect DB at test exit
Logger:
* Avoid sending console use to logger once we have ended the log

Test fixes: use Prisma v4.8.1 to avoid handle leak; avoid sending console to logger after log.end() is called

---

server/db/connection/DBConnection.ts
server/db/connection/DBObject.ts
server/graphql/schema/ingestion/resolvers/mutations/ingestData.ts
server/utils/migration/ModelMigration.ts
server/utils/migration/SceneMigration.ts
server/workflow/impl/Packrat/WorkflowUtil.ts

Migration:
* Compute asset map (filename -> idAsset); pass this to WorkflowUtil.computeModelMetrics
* Don't set model title
* If no master model is supplied to scene migration, look for one among the scene children of the item parent
Workflow:
* Allow for optional assetMap to be passed into computeModelMetrics, which in turn gets passed to JobCookSIPackratInspectOutput.persist, for proper construction of ModelMaterialUVMaps and ModelMaterialChannels
DBAPI:
* Simplify DB error logging to make things easier to read
GraphQL:
* Only query EDAN once when computing identifiers for ingested subjects

Migration: compute asset map needed by WorkflowUtil.computeModelMetrics, etc.

---

client/src/pages/Repository/components/DetailsView/DetailsThumbnail.tsx
client/src/pages/Repository/components/DetailsView/index.tsx
client/src/pages/Repository/hooks/useDetailsView.ts
client/src/types/graphql.tsx
server/db/api/Model.ts
server/db/api/Scene.ts
server/graphql/api/queries/systemobject/getVoyagerParams.ts
server/graphql/schema.graphql
server/graphql/schema/systemobject/queries.graphql
server/graphql/schema/systemobject/resolvers/index.ts
server/graphql/schema/systemobject/resolvers/mutations/updateObjectDetails.ts
server/graphql/schema/systemobject/resolvers/queries/getVoyagerParams.ts
server/job/impl/Cook/JobCookSIPackratInspect.ts
server/tests/db/dbcreation.test.ts
server/types/graphql.ts
server/utils/migration/SceneMigration.ts

Migration:
* Handle variable Cook output for fields like "dracoCompressed" -- coerce numeric input to boolean, before attempting to write to the database
* Retry fetching content 3 times, with 1.5 seconds delay between requests, before giving up on scene migration
GraphQL:
* Implemented getVoyagerParams(), which computes the document, path, and idSystemObjectScene needed to render Voyager Story on both Scene and Model pages. For a given idSystemObject, we compute what kind of object this is. If it's a scene, use that object.  If it's a model, determine the model purpose; for master models, pick the newest child scene; for Voyager models, pick the newest parent scene; for all the rest, pick the newest scene from parents, and then from children; for non-scenes/non-models, return an error. …

Add Model Viewer (Voyager) to model details page; address migration error handling of dracoCompressed

---

server/db/api/CookResource.ts
server/db/index.ts
server/db/prisma/schema.prisma
server/db/sql/scripts/Packrat.ALTER.sql
server/db/sql/scripts/Packrat.DATA.sql
server/db/sql/scripts/Packrat.DROP.sql
server/db/sql/scripts/Packrat.SCHEMA.sql
server/http/index.ts
server/http/routes/resources.ts
server/job/impl/Cook/CookResource.ts
server/job/impl/Cook/JobCook.ts
server/job/impl/Cook/index.ts
server/job/impl/NS/JobPackrat.ts
server/job/interface/IJob.ts
server/package.json
server/storage/impl/LocalStorage/OCFLInventory.ts
server/storage/impl/LocalStorage/OCFLObject.ts
server/tests/graphql/queries/asset/getAssetVersionsDetails.test.ts
yarn.lock

Added support for dynamic Cook resource assignment in CookJobs. When a job is created, available Cook resources are queried to find the best fit for the current job type looking at the resource's configuration and # of jobs running/waiting. This allows for better utilization of Cook resources and load balancing for concurrent jobs.
Currently supports the following jobs:
- inspection
- scene_generation
- generate_downloads
- photogrammetry
Additionally, a public endpoint was created allowing other services (i.e. Cook, Voyager, etc.) to query Packrat to get the best fit Cook resource. This is useful for various automations including Photogrammetry.
Example:
```
https://packrat.si.edu/resources/cook?job=inspection
``` 
Developers need to add the CookResource table to their local DB. See …

DPO3DPKRT-767/Support Multiple Cook Resources

---

server/utils/nameHelpers.ts

EDAN titles containing non-ASCII characters were causing issues with scene generation recipes. Updated sanitization regex.

DPO3DPKRT-776/non ascii characters for derivatives

---

server/graphql/schema/asset/resolvers/mutations/uploadAsset.ts
server/job/impl/Cook/JobCookSIPackratInspect.ts
server/storage/interface/AssetStorageAdapter.ts
server/tests/jest.config.js
server/tests/storage/impl/LocalStorage/OCFL.test.ts
server/tests/utils/helpers.test.ts
server/utils/parser/csvParser.ts
server/utils/zipFile.ts
server/utils/zipStream.ts
server/workflow/impl/Packrat/WorkflowUpload.ts

Some uses of file streams were not logging errors or were lacking details. Added error handling and ensuring all streams always log errors.

DPO3DPKRT-774/streams not reporting generated errors

---

server/db/api/AssetVersion.ts
server/job/impl/Cook/JobCook.ts
server/storage/impl/LocalStorage/LocalStorage.ts
server/storage/interface/AssetStorageAdapter.ts
server/utils/parser/svxReader.ts

In rare cases Packrat would miss a 'success' message from Cook and continue polling until timeout. Catching ranges of status codes to ensure all responses from Cook are handled.

DPO3DPKRT-761/improved cook responses for generate downloads

---

server/db/api/Asset.ts
server/db/api/JobRun.ts
server/db/api/Scene.ts
server/db/api/Workflow.ts
server/db/api/WorkflowReport.ts
server/graphql/schema/asset/resolvers/mutations/uploadAsset.ts
server/job/impl/Cook/JobCook.ts
server/job/impl/Cook/JobCookSIGenerateDownloads.ts
server/job/impl/Cook/JobCookSIVoyagerScene.ts
server/job/impl/NS/JobPackrat.ts
server/workflow/impl/Packrat/WorkflowJob.ts

Generate downloads now verifies assets returning from Cook meet basic requirements (e.g. naming) before accepting them for ingestion.

[DPO3DPKRT-788] Updating assets from Cook with diff names fails

---

server/job/impl/Cook/JobCook.ts
server/job/impl/NS/JobPackrat.ts

The 'Workflow' view in Packrat now provides access to Cook Job reports from when the job first starts and continues to update it while the job is running.
Additional QoL additions added as well:
Cook Job Id now listed in reports
all errors appended to reports, etc.

[DPO3DPKRT-799] Cook reports not showing in Workflow view

---

client/src/api/index.ts
client/src/pages/Repository/components/DetailsView/index.tsx
server/collections/impl/PublishScene.ts
server/db/api/Asset.ts
server/db/api/JobRun.ts
server/db/api/Model.ts
server/db/api/Project.ts
server/db/api/Scene.ts
server/db/api/SystemObjectVersion.ts
server/event/interface/EventEnums.ts
server/http/index.ts
server/http/routes/WebDAVServer.ts
server/http/routes/api/generateDownloads.ts
server/job/impl/Cook/JobCookSIGenerateDownloads.ts
server/report/impl/Report.ts
server/tests/cache/VocabularyCache.test.ts
server/utils/helpers.ts
server/utils/localStore.ts
server/utils/logger.ts
server/workflow/impl/Packrat/WorkflowEngine.ts
server/workflow/impl/Packrat/WorkflowIngestion.ts
server/workflow/impl/Packrat/WorkflowJob.ts
server/workflow/impl/Packrat/WorkflowUpload.ts
server/workflow/interface/IWorkflow.ts
server/workflow/interface/IWorkflowEngine.ts

- Fixed issues with the user/request context being lost (e.g. HTTP requests, WebDAV, etc.)
- Improved logging and reports for auditing
- New button on the Scene details tab for manually (re)generating downloads. 
Note: The downloads button is enabled/disabled depending on the state of the scene and prevents creating downloads if the job is running or the scene is lacking basic requirements. (e.g. QC'd) It may require a page refresh, but the backend will prevent invalid requests with client-side toasts.

DPO3DPKRT-798/manual execution generate downloads

---

client/src/pages/Ingestion/components/SubjectItem/SubjectList.tsx
client/src/pages/Ingestion/components/SubjectItem/SubjectListItem.tsx

When searching for a Subject during ingestion the collection ID is shown to help with selecting a Subject.

DPO3DPKRT-755/show EDAN subject id on ingest

---

client/src/components/controls/IndentedReadOnlyRow.tsx
client/src/components/controls/LabelTooltipText.tsx
client/src/components/shared/FieldType.tsx
client/src/pages/Ingestion/components/Metadata/Scene/SceneDataForm.tsx
client/src/pages/Repository/components/DetailsView/DetailsTab/CaptureDataDetails.tsx
client/src/pages/Repository/components/DetailsView/DetailsTab/ModelDetails.tsx
client/src/pages/Repository/components/DetailsView/DetailsTab/SceneDetails.tsx

- CSS 'color' properties now correctly use central theme colors where the value was set to 'auto'

DPO3DPKRT-85/invalid value of 'auto' used for 'color' CSS properties

---

client/src/pages/Repository/components/DetailsView/DetailsTab/AssetGrid.tsx
client/src/pages/Repository/components/DetailsView/DetailsTab/index.tsx
client/src/pages/Repository/components/DetailsView/DetailsThumbnail.tsx

- adjusted styling and format of Asset table in Scene Details to fit the page.
- introduced better default columns to view for scene assets. still customizable. reset cookies to see.
- fixed width of voyager thumbnail to use entire width section.

DPO3DPKRT-815/Scene details asset table too wide

---

client/src/pages/Repository/components/DetailsView/DetailsThumbnail.tsx
server/graphql/schema/asset/resolvers/mutations/uploadAsset.ts
server/http/routes/api/generateDownloads.ts
server/job/impl/Cook/JobCookSIPackratInspect.ts
server/storage/impl/LocalStorage/LocalStorage.ts
server/storage/interface/AssetStorageAdapter.ts
server/utils/helpers.ts

- All model uploads now using streaming for zips
- Using 'staging' for temporary files instead of system temp directories
- Fixed losing user context when uploading assets
- Removes Voyager Explorer when Story is open

DPO3DPKRT-802/large model zip failure

---

client/src/pages/Admin/components/AdminToolsView.tsx
server/job/impl/Cook/JobCookSIGenerateDownloads.ts
tsconfig.json

Scenes with additional files (articles, images, etc.) no longer fail validation when generating downloads.

DPO3DPKRT-836/verifying cook response fails with article assets

---

client/src/api/index.ts
client/src/pages/Admin/components/AdminToolsView.tsx
client/src/pages/Repository/components/DetailsView/DetailsThumbnail.tsx
client/src/pages/Repository/components/DetailsView/index.tsx
server/collections/impl/EdanCollection.ts
server/config/index.ts
server/db/api/Asset.ts
server/db/api/AssetVersion.ts
server/db/api/JobRun.ts
server/db/api/Model.ts
server/db/api/ModelSceneXref.ts
server/db/api/WorkflowReport.ts
server/db/sql/scripts/Packrat.DATA.sql
server/http/index.ts
server/http/routes/api/generateDownloads.ts
server/http/routes/api/generateVoyagerScene.ts
server/http/routes/api/project.ts
server/job/impl/Cook/JobCook.ts
server/job/impl/Cook/JobCookSIGenerateDownloads.ts
server/job/impl/Cook/JobCookSIVoyagerScene.ts
server/tests/collections/EdanCollection.test.ts
server/workflow/impl/Packrat/WorkflowEngine.ts
server/workflow/impl/Packrat/WorkflowJob.ts
server/workflow/interface/IWorkflowEngine.ts

- Support for (re)generating a scene from a Master model's detail page
- Updated scene summary to include master model details
- Various bug fixes within workflow and Prisma

(0.9.22) Manual Scene (Re)generation

---

client/src/pages/Admin/components/AdminToolsView.tsx
server/http/routes/api/project.ts

- support column references 3 levels deep
- better handling of links in row data
- support for latest SceneSummary definitions

DPO3DPKRT-854/Invalid Handling of Scene Summary

---

client/src/pages/Admin/components/AdminToolsView.tsx

- Export scene summary data in the 'batch tool' table

DPO3DPKRT-857/CSV export for scene summary

---

client/src/pages/Admin/components/AdminToolsView.tsx

- Strings with commas or quotes (e.g. names) no longer affect CSV formatting
- Introduced 'link' column in export directing to Scene detail page

DPO3DPKRT-858/CSV export failing names with commas

---

server/config/index.ts
server/http/routes/sandbox.ts
server/records/logger/log.ts
server/records/notify/notify.ts
server/records/notify/notifyEmail.ts
server/records/notify/notifyShared.ts
server/records/notify/notifySlack.ts
server/records/recordKeeper.ts
server/records/utils/rateManager.ts

Notification support sending Slack messages
- Messages to specific channels with formatted output
- Custom icons based on message type
- Tagging users on relevant messages for mentions
- Rate management w/ adaptive burst speeds
- Internal throughput testing routines

DPO3DPKRT-863/Slack Notifications

---

server/graphql/schema/asset/resolvers/mutations/uploadAsset.ts
server/job/impl/Cook/JobCook.ts
server/job/impl/Cook/JobCookSIPackratInspect.ts
server/workflow/impl/Packrat/WorkflowEngine.ts

Verify model inspection results from Cook
- Fail models with invalid vertices, faces, or edges
- Fail models with invalid zip packages
- Fail models with missing materials, UVs, etc.
- Support for legacy and new Blender-centric inspection reports

DPO3DPKRT-882/Robust Cook Inspection Responses

---

server/job/impl/Cook/JobCookSIPackratInspect.ts

Support for new 'error' attribute for materials during inspection
- Consolidate material errors and fail as needed

DPO3DPKRT-882/Hotfix Update for Cook Material Report

---

client/src/components/shared/AssetIdentifiers.tsx
client/src/pages/Ingestion/components/Metadata/Control/SubtitleControl.tsx
client/src/pages/Ingestion/components/Metadata/Model/index.tsx
client/src/pages/Ingestion/components/Metadata/Photogrammetry/index.tsx
client/src/pages/Ingestion/components/Metadata/Scene/SceneDataForm.tsx
client/src/pages/Ingestion/components/Metadata/Scene/index.tsx
client/src/pages/Ingestion/components/Metadata/index.tsx

Blocking user input while ingesting
- All input fields disabled during ingestion (checkboxes, text field, etc.)
- Notice presented to user to tell them to wait until done
- Added 'disabled' property to (sub)components of Metadata page

DPO3DPKRT-861/Block Input During Ingestion

---

server/job/impl/Cook/JobCook.ts

Resolve Cook jobs timing out
- Better handling of states returned by Cook and recording success/failure/etc.
- Catch unsupported states and output details

DPO3DPKRT-889/cook-scene-gen-job-timeout

---

client/src/store/metadata/metadata.defaults.ts

- Issue related to earlier fixed bug with long filenames in Cook
- Provided a more robust check for ingest Model date metadata

DPO3DPKRT-906/Scene Generation Not Receiving Textures
